development:
  adapter: mysql2
  database: urlshortener_dev
  username: root
  password: root
  host: localhost
test:
  adapter: mysql2
  database: urlshortener_test
  username: root
  password: root
  host: localhost
production:
  adapter: mysql2
  database: urlshortener_production
  username: root
  password: root
  host: localhost
